### PR TITLE
made function parameters into snippets

### PR DESCRIPTION
**Pull request by amp343**

### CODE REVIEW

**Comment by Azakur4** [comment]
Nice work man the only think now is remove the property in the json i think

**Comment by amp343** [comment]
Took `parameters` out of the json. 

Also made a small change to the `@notShowAutocomplete()` logic, since by default it was trying to autocomplete empty requests (characters like `.` or `|`) and also strings inside of quotes. Added a bit of logic to say "don't autocomplete function names that are inside of quote scopes." Feel free to correct if that's not how you envisioned it.

**Comment by Azakur4** [comment]
Nice man i can considere this like a finish work and merge?

**Comment by amp343** [comment]
It seems to work ok for me -- but try it out, see if you like how it works. If you think the function completion is working well, go ahead!

**Comment by Azakur4** [comment]
ok i will try it

**Comment by Azakur4** [comment]
Thanks nice work, merged!
I will release a new version with this update thanks again.

**Pull request merged**
